
# Input
HEADERS += \
    $$PWD/src/qtwidgetsextra.h \
    $$PWD/src/painting/qtcolorutils.h \
    $$PWD/src/painting/qtcolorpalette.h \
    $$PWD/src/mainwindow/qtdocktabbar.h \
    $$PWD/src/mainwindow/qtdockwidget.h \
    $$PWD/src/mainwindow/qtdockwidgettitlebar.h \
    $$PWD/src/mainwindow/qtdocksidebar.h \
    $$PWD/src/mainwindow/qtmainwindow.h \
    $$PWD/src/mainwindow/qtwindowmanager.h \
    $$PWD/src/indicators/qtswitchbutton.h \
    $$PWD/src/indicators/qtstateindicator.h \
    $$PWD/src/itemviews/qtitemmodelutility.h \
    $$PWD/src/itemviews/delegates/qtactionitemdelegate.h \
    $$PWD/src/itemviews/delegates/qtcomboboxitemdelegate.h \
    $$PWD/src/itemviews/delegates/qtcompositeitemdelegate.h \
    $$PWD/src/itemviews/delegates/qtcounteritemdelegate.h \
    $$PWD/src/itemviews/delegates/qtprogressitemdelegate.h \
    $$PWD/src/itemviews/delegates/qtrichtextitemdelegate.h \
    $$PWD/src/itemviews/delegates/qtsheetitemdelegate.h \
    $$PWD/src/itemviews/delegates/qtvariantitemdelegate.h \
    $$PWD/src/itemviews/delegates/qtvarianttypedelegate.h \
    $$PWD/src/itemviews/delegates/qtmenuitemdelegate.h \
    $$PWD/src/itemviews/models/qtenumlistmodel.h \
    $$PWD/src/itemviews/models/qttablemodelexporter.h \
    $$PWD/src/itemviews/models/qttablemodelexporterdialog.h \
    $$PWD/src/itemviews/models/qttablemodelexporterfactory.h \
    $$PWD/src/itemviews/models/qttablemodelexporterplugin.h \
    $$PWD/src/itemviews/models/qttextcodecmodel.h \
    $$PWD/src/itemviews/models/qtcolumnproxymodel.h \
    $$PWD/src/itemviews/models/qtcompositeproxymodel.h \
    $$PWD/src/itemviews/models/qtvariantlistmodel.h \
    $$PWD/src/itemviews/models/qtcheckableproxymodel.h \
    $$PWD/src/itemviews/models/qtobjectlistmodel.h \
    $$PWD/src/itemviews/models/qtobjecttreemodel.h \
    $$PWD/src/itemviews/models/qtheaderproxymodel.h \
    $$PWD/src/itemviews/models/qtrowproxymodel.h \
    $$PWD/src/itemviews/models/qtitemfilter.h \
    $$PWD/src/itemviews/views/qtcustomheaderview.h \
    $$PWD/src/itemviews/views/qtitemviewnavigator.h \
    $$PWD/src/itemviews/views/qtitemviewcontroller.h \
    $$PWD/src/itemviews/views/qtrangenavigator.h \
    $$PWD/src/itemviews/views/qtcrumbbar.h \
    $$PWD/src/widgets/qtaboutdialog.h \
    $$PWD/src/widgets/qtcolorbutton.h \
    $$PWD/src/widgets/qtcolorcombobox.h \
    $$PWD/src/widgets/qtcontentview.h \
    $$PWD/src/widgets/qtlineboxedit.h \
    $$PWD/src/widgets/qtnotificationbar.h \
    $$PWD/src/widgets/qtoptionswidget.h \
    $$PWD/src/widgets/qtpathlineedit.h \
    $$PWD/src/widgets/qtshortcutedit.h \
    $$PWD/src/widgets/qtslidecontroller.h \
    $$PWD/src/widgets/qtsplashwidget.h \
    $$PWD/src/widgets/qtsyntaxhighlighter.h \
    $$PWD/src/widgets/qtenums.h \
    $$PWD/src/widgets/qteditdialog.h \
    $$PWD/src/widgets/qthsvrectpicker.h \
    $$PWD/src/widgets/qthsvradialpicker.h \
    $$PWD/src/widgets/qtcolorselector.h \
    $$PWD/src/widgets/qtlongspinbox.h \
    $$PWD/src/widgets/qttextspinbox.h \
    $$PWD/src/widgets/qtcolorgrid.h \
    $$PWD/src/widgets/qtcolorgrid_p.h \
    $$PWD/src/widgets/qtcolortriangle.h \
    $$PWD/src/widgets/qtpatternedit.h \
    $$PWD/src/widgets/qtspanslider.h \
    $$PWD/src/widgets/qtdaterange.h \
    $$PWD/src/widgets/qtdaterangeedit.h \
    $$PWD/src/widgets/qtmultiprogressdialog.h \
    $$PWD/src/widgets/qtplaceholdereffect.h \
    $$PWD/src/widgets/qtprogresseffect.h \
    $$PWD/src/widgets/qtmessagelogview.h \
    $$PWD/src/widgets/qtmessagelogmodel.h \
    $$PWD/src/widgets/qtmessagelogwidget.h \
    $$PWD/src/widgets/qtoverviewwidget.h \
    $$PWD/src/widgets/qtbuttonlocker.h \
    $$PWD/src/widgets/qtslidebutton.h \
    $$PWD/src/widgets/qtslidebutton_p.h \
    $$PWD/src/widgets/qtslidecheckbox.h \
    $$PWD/src/widgets/qtfloatingtoolbutton.h \
    $$PWD/src/widgets/qtsnackbar.h \
    $$PWD/src/widgets/qtcardwidget.h \
    $$PWD/src/itemviews/models/qtrevertibleproxymodel.h \
    $$PWD/src/itemviews/models/qtcachingproxymodel.h \
    $$PWD/src/itemviews/models/qttreeproxymodel.h \
    $$PWD/src/widgets/qtspinboxedit.h \
    $$PWD/src/painting/qtpaintutils.h \
    $$PWD/src/itemviews/delegates/qtwidgetitemdelegate.h


SOURCES += \
    $$PWD/src/painting/qtcolorutils.cpp \
    $$PWD/src/painting/qtcolorpalette.cpp \
    $$PWD/src/painting/qtcolorpaletteformats.cpp \
    $$PWD/src/mainwindow/qtdocktabbar.cpp \
    $$PWD/src/mainwindow/qtdockwidget.cpp \
    $$PWD/src/mainwindow/qtdockwidgettitlebar.cpp \
    $$PWD/src/mainwindow/qtdocksidebar.cpp \
    $$PWD/src/mainwindow/qtmainwindow.cpp \
    $$PWD/src/mainwindow/qtwindowmanager.cpp \
    $$PWD/src/indicators/qtswitchbutton.cpp \
    $$PWD/src/indicators/qtstateindicator.cpp \
    $$PWD/src/itemviews/delegates/qtactionitemdelegate.cpp \
    $$PWD/src/itemviews/delegates/qtcomboboxitemdelegate.cpp \
    $$PWD/src/itemviews/delegates/qtcompositeitemdelegate.cpp \
    $$PWD/src/itemviews/delegates/qtcounteritemdelegate.cpp \
    $$PWD/src/itemviews/delegates/qtprogressitemdelegate.cpp \
    $$PWD/src/itemviews/delegates/qtrichtextitemdelegate.cpp \
    $$PWD/src/itemviews/delegates/qtsheetitemdelegate.cpp \
    $$PWD/src/itemviews/delegates/qtvariantitemdelegate.cpp \
    $$PWD/src/itemviews/delegates/qtvarianttypedelegate.cpp \
    $$PWD/src/itemviews/delegates/qtmenuitemdelegate.cpp \
    $$PWD/src/itemviews/models/qtenumlistmodel.cpp \
    $$PWD/src/itemviews/models/qtcolumnproxymodel.cpp \
    $$PWD/src/itemviews/models/qttextcodecmodel.cpp \
    $$PWD/src/itemviews/models/qtcompositeproxymodel.cpp \
    $$PWD/src/itemviews/models/qttablemodelexporter.cpp \
    $$PWD/src/itemviews/models/qttablemodelexporterfactory.cpp \
    $$PWD/src/itemviews/models/qttablemodelexporterdialog.cpp \
    $$PWD/src/itemviews/models/qtvariantlistmodel.cpp \
    $$PWD/src/itemviews/models/qtcheckableproxymodel.cpp \
    $$PWD/src/itemviews/models/qtobjectlistmodel.cpp \
    $$PWD/src/itemviews/models/qtobjecttreemodel.cpp \
    $$PWD/src/itemviews/models/qtheaderproxymodel.cpp \
    $$PWD/src/itemviews/models/qtrowproxymodel.cpp \
    $$PWD/src/itemviews/models/qtitemfilter.cpp \
    $$PWD/src/itemviews/views/qtcustomheaderview.cpp \
    $$PWD/src/itemviews/views/qtitemviewnavigator.cpp \
    $$PWD/src/itemviews/views/qtitemviewcontroller.cpp \
    $$PWD/src/itemviews/views/qtrangenavigator.cpp \
    $$PWD/src/itemviews/views/qtcrumbbar.cpp \
    $$PWD/src/widgets/qtaboutdialog.cpp \
    $$PWD/src/widgets/qtcolorbutton.cpp \
    $$PWD/src/widgets/qtcolorcombobox.cpp \
    $$PWD/src/widgets/qtcontentview.cpp \
    $$PWD/src/widgets/qtlineboxedit.cpp \
    $$PWD/src/widgets/qtnotificationbar.cpp \
    $$PWD/src/widgets/qtoptionswidget.cpp \
    $$PWD/src/widgets/qtpathlineedit.cpp \
    $$PWD/src/widgets/qtshortcutedit.cpp \
    $$PWD/src/widgets/qtslidecontroller.cpp \
    $$PWD/src/widgets/qtsplashwidget.cpp \
    $$PWD/src/widgets/qtsyntaxhighlighter.cpp \
    $$PWD/src/widgets/qtenums.cpp \
    $$PWD/src/widgets/qteditdialog.cpp \
    $$PWD/src/widgets/qthsvrectpicker.cpp \
    $$PWD/src/widgets/qthsvradialpicker.cpp \
    $$PWD/src/widgets/qtcolorselector.cpp \
    $$PWD/src/widgets/qtlongspinbox.cpp \
    $$PWD/src/widgets/qttextspinbox.cpp \
    $$PWD/src/widgets/qtcolorgrid.cpp \
    $$PWD/src/widgets/qtcolortriangle.cpp \
    $$PWD/src/widgets/qtpatternedit.cpp \
    $$PWD/src/widgets/qtspanslider.cpp \
    $$PWD/src/widgets/qtdaterange.cpp \
    $$PWD/src/widgets/qtdaterangeedit.cpp \
    $$PWD/src/widgets/qtmultiprogressdialog.cpp \
    $$PWD/src/widgets/qtplaceholdereffect.cpp \
    $$PWD/src/widgets/qtprogresseffect.cpp \
    $$PWD/src/widgets/qtmessagelogview.cpp \
    $$PWD/src/widgets/qtmessagelogmodel.cpp \
    $$PWD/src/widgets/qtmessagelogwidget.cpp \
    $$PWD/src/widgets/qtoverviewwidget.cpp \
    $$PWD/src/widgets/qtbuttonlocker.cpp \
    $$PWD/src/widgets/qtslidebutton.cpp \
    $$PWD/src/widgets/qtslidecheckbox.cpp \
    $$PWD/src/widgets/qtfloatingtoolbutton.cpp \
    $$PWD/src/widgets/qtsnackbar.cpp \
    $$PWD/src/widgets/qtcardwidget.cpp \
    $$PWD/src/itemviews/models/qtrevertibleproxymodel.cpp \
    $$PWD/src/itemviews/models/qtcachingproxymodel.cpp \
    $$PWD/src/itemviews/models/qttreeproxymodel.cpp \
    $$PWD/src/widgets/qtspinboxedit.cpp \
    $$PWD/src/painting/qtpaintutils.cpp \
    $$PWD/src/itemviews/delegates/qtwidgetitemdelegate.cpp

RESOURCES += \
    $$PWD/qtwidgetsextra.qrc
